### PR TITLE
Support for ag-grid bundle usage

### PR DESCRIPTION
**Pull request by arpit-agarwal**
This for issue #15

### CODE REVIEW

**Comment by ceolter** [comment]
why does this change make a difference?

either version should work?

**Comment by arpit-agarwal** [comment]
This change allow to reference ag-grid as bundle as it is not asking for ag-grid/main explicity in module definition. This change should be compatable for pepole want to use ag-grid as non bundle via adding appropertie entry in system.js

**Comment by ceolter** [comment]
the ag-grid-ng2 project is not available as a bundle. are you saying you want to use ag-grid.js (the bundled ag-grid) with this project?

**Comment by arpit-agarwal** [comment]
Exactly. We want to use ag-grid as bundle

**Comment by ceolter** [comment]
there is no bundle for ag-grid-ng2, only for ag-grid

you can understand why here:
https://www.ag-grid.com/understanding-packaging-for-javascript-typescript-commonjs-and-everything-else/

**Comment by arpit-agarwal** [comment]
I am not asking for bundle for ag-grid-ng2. I want to use ag-grid as a bundle when using ag-grid-ng2 as non bundle.  This usecase is not working at the moment with systemJS configuration for ng2 rc3 based project

**Comment by ceolter** [comment]
yes i understand you don't want ag-grid-ng2 as a bundle. but my question is, why are yous mixing bundled and non-bundled, if using non-bundled ag-grid-ng2 (and i presume angular), then why are you using bundled ag-grid? my expectation is you use non-bundled everything.

**Comment by ceolter** [comment]
ps - my hesitation is that this change, although it might fix your scenario, might break for someone else, who uses bower for example

**Comment by arpit-agarwal** [comment]
I am using bundled angular2 and would like to use bundled ag-grid to reduce 75 request to 1. ag-grid-ng2 is not bundled and have just 1/2 request so I am ok for that. 
I see this will work folks using npm.  Not sure how does bower break. 
What are my options here ...move dependencies of ag-grid-ng2 to point to my forked version ?

**Comment by ceolter** [comment]
yes you can do that . . . . . or just copy the ag-grid-ng2 code into your project.

do you actually have it working against your forked version? i'd be surprised if you did - the ag-grid-ng2 project uses the standard ng2, my understanding is you can't mix the annotation based approach with the plan javascritp approach.

**Comment by ceolter** [comment]
the ag-grid-ng2 code is very small

**Comment by arpit-agarwal** [comment]
Yup. I am able to use angular umd with my forked version after rc2 release.

**Comment by seanlandsman** [comment]
With AOT etc the standard for ng2, we wont be pursuing this side of this. Closing at the fork seems to be do the trick for your usecase.

**Pull request closed without merging**
